version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    build: ./db
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    networks:
      - backend


  python:
    image: python:3.5
    container_name: python
    build: ./app
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
