version: "3.9"
services:
  postgres:
    container_name: postgres
    build: ./db
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      start_period: 5s
      retries: 4

  python:
    container_name: python
    build: ./app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge