name: Django CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'app/python-postgres-user-registration/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'app/python-postgres-user-registration/**'

jobs:
  app-test:
    runs-on: ubuntu-latest
    
    env:
      POSTGRES_USER    : postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_HOST    : localhost
      
    services:
      postgres:
        image: postgres:9.5
        env:       
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_USER    : ${{ env.POSTGRES_USER }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
    defaults:
        run:
          working-directory: app/python-postgres-user-registration/
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    
   
    steps:
    - name: Copy repo
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
            
    - name: Create table
      run: psql -U postgres -h localhost    < ../../create_table_users.sql
      env:
        POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
        PGPASSWORD   : ${{ env.POSTGRES_PASSWORD }}
        POSTGRES_USER: ${{ env.POSTGRES_USER }}
    - name: Run Tests
      run: |
        python app.py test
      env:
        PG_HOST: ${{ env.POSTGRES_HOST }}

