name: Django CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'app/python-postgres-user-registration/**'
  pull_request:
    branches: [ main ]
    

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
    defaults:
        run:
          working-directory: app/python-postgres-user-registration/
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    
   
    steps:
    - name: Copy repo
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
            
    - name: Create table
      run: psql  -U postgres < ../../create_table_users.sql
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
    - name: Run Tests
      run: |
        python app.py test
        
