name: terraform-test

on:
  push:
    branches: [ main ]
    paths: 
      - 'main.tf'
      - 'variables.tf'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        terraform_version: [1.0.11, 1.2.2]
        
    steps:
      - name: Copy Repo
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform-version }}
          
      - name: Terraform Reformat 
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
     
      - name: Successs message
        run: echo "Terraform test success!:)"
